% Example: For source set { 0-3 R, 0-2 L, 0-2 C }.
rlc_store = [ 3, 2, 2 ];
kit_counts = count_kits( rlc_store );
assert...
( ...
    all( kit_counts.rlc_count == ( 1 : 7 )' ) ...
 && all( kit_counts.kit_count == [ 3 6 8 8 6 3 1 ]' ) ...
)
fprintf( "All ok\n" );