nets_1_1_1 = EnumerateNetworks( [1 2], {}, 3, struct( 'R', 1, 'L', 1, 'C', 1 ), false );

nets_1_1_1_as_string = nets_to_string( nets_1_1_1 );
load( "data/ref_nets_1_1_1_as_string.mat" );

assert( nets_1_1_1_as_string == ref_nets_1_1_1_as_string, "Fail 1" );

function s = nets_to_string( nets )
    s = "";
    for ni = 1 : length( nets )
        s = s ...
            + sprintf( "net %d : ", ni )  ...
            + net_to_string( nets{ ni } ) ...
            + newline;
    end
end

function s = net_to_string( net )
    nb = length( net.edges ); 
    s = sprintf( "%d = ", nb ); 
    for bi = 1 : nb
        s = s ...
            + sprintf ...
              ( ...
                "{%d,%d,%s} ", ...
                net.edges{ bi } { 1 }, ...
                net.edges{ bi } { 2 }, ...
                net.edges{ bi } { 3 }  ...
              );
    end
end
